---
- hosts: security_group_Webserver
  remote_user:  ec2-user
  sudo: True
  vars:
   user_list: papa, papa1, papa2, papa3

  tasks:
  - name: Adding Elastic Ip address
    ec2_eip:
     aws_access_key: AKIAJKQIDA2EBEI2MHQQ
     aws_secret_key: 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
     instance_id: i-0f4ff25e0cabe3d69
     region: eu-west-1
     state: present
