---
- hosts: apache
  remote_user:  root
  vars:
   user_list: papa, papa1, papa2, papa3

  tasks:
  - name: Creating User in nodes
    user: name={{item}} state=present
    with_items:
    - papa
    - papa1
    - papa2
    - papa3

