- name: docker Management tasks
  hosts: Apache
## chnages there
  tasks:
  - name: data container
    docker:
      name: mydata
      image: hello-world
      state: present
      volumes:
      - /nfs
