- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: id_rsa
    instance_type: t2.micro
    security_group: my_securitygroup
    image: ami-b63769a1
    region: ap-northeast-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         aws_access_key: AKIAISYNP2YHFGD2X5QA
         aws_secret_key: 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
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
          
    - name: Print all EC2 variable
      debug: var=ec2
