---
- name: Testing Loop
  hosts: Apache
  remote_user: root
#test
  tasks:
  - name: Loop over environment facts
    debug: msg={{item.key}}={{item.value}}
    with_dict: ansible_env

  - name: Loop to copy file on reote Machine
    copy: src={{item}} dest=/tmp
    with_fileglob: "/etc/*.conf"

