Vagrant.configure(2) do |config|
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "hashicorp/precise32"
    webserver.vm.network "private_network", ip: "192.168.0.2"
    webserver.vm.hostname = "webserver"
  end
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "hashicorp/precise32"
    ansible.vm.network "private_network", ip: "192.168.0.254"
    ansible.vm.hostname = "ansible"
  end

config.vm.define "rishi" do |rishi|
    rishi.vm.box = "ubuntu/trusty32"
    rishi.vm.network "private_network", ip: "192.168.0.26"
    rishi.vm.hostname = "rishi"
    rishi.vm.boot_timeout = 1000
  end
end
