---
# tasks file for aws.facts
- name: Gather EC2 facts.
  ec2_remote_facts:
#    aws_secret_key: "{{ vault.aws_secret_key }}"
#    aws_access_key: "{{ vault.aws_access_key }}"
#    region: "{{ vault.region }}"

    aws_secret_key: 
    aws_access_key: 
    region: eu-west-1
    filters:
      "tag:backup": "yes"
  register: ec2_facts

- name: Print facts
  debug:
    msg: "{{ ec2_facts }}"
